/* 自动生成，来源：pinyin-engine/src/shuangpin.py + flypy scheme（data/double_pinyin_flypy.schema.yaml）。
 * 不要手改——跑 `python3 c/tools/gen_shuangpin_table.py > c/src/shuangpin_data.h` 重新生成。
 *
 * 穷举全部 26x26=676 种 2 键组合的解码结果（已验证组间解码互不
 * 干扰，见生成脚本顶部说明），下标 = (第一个键-'a')*26 + (第二个键-'a')。
 * 每项是解码出的拼音片段（NUL 结尾 ASCII 字符串，不含分隔符）。 */
#define CJ_SHUANGPIN_FLYPY_MAX_LEN 6
static const char CJ_SHUANGPIN_FLYPY_TABLE[676][7] = {
    "aa", /* aa */
    "ain", /* ab */
    "ao", /* ac */
    "ai", /* ad */
    "ae", /* ae */
    "aen", /* af */
    "aeng", /* ag */
    "ang", /* ah */
    "ai", /* ai */
    "an", /* aj */
    "aing", /* ak */
    "auang", /* al */
    "aian", /* am */
    "an", /* an */
    "ao", /* ao */
    "aie", /* ap */
    "aiu", /* aq */
    "ar", /* ar */
    "aong", /* as */
    "ave", /* at */
    "au", /* au */
    "av", /* av */
    "aei", /* aw */
    "aia", /* ax */
    "aun", /* ay */
    "aou", /* az */
    "ba", /* ba */
    "bin", /* bb */
    "bao", /* bc */
    "bai", /* bd */
    "be", /* be */
    "ben", /* bf */
    "beng", /* bg */
    "bang", /* bh */
    "bi", /* bi */
    "ban", /* bj */
    "bing", /* bk */
    "buang", /* bl */
    "bian", /* bm */
    "biao", /* bn */
    "bo", /* bo */
    "bie", /* bp */
    "biu", /* bq */
    "br", /* br */
    "bong", /* bs */
    "bve", /* bt */
    "bu", /* bu */
    "bv", /* bv */
    "bei", /* bw */
    "bia", /* bx */
    "bun", /* by */
    "bou", /* bz */
    "ca", /* ca */
    "cin", /* cb */
    "cao", /* cc */
    "cai", /* cd */
    "ce", /* ce */
    "cen", /* cf */
    "ceng", /* cg */
    "cang", /* ch */
    "ci", /* ci */
    "can", /* cj */
    "cuai", /* ck */
    "cuang", /* cl */
    "cian", /* cm */
    "cn", /* cn */
    "cuo", /* co */
    "cie", /* cp */
    "ciu", /* cq */
    "cuan", /* cr */
    "cong", /* cs */
    "cuie", /* ct */
    "cu", /* cu */
    "cui", /* cv */
    "cei", /* cw */
    "cua", /* cx */
    "cun", /* cy */
    "cou", /* cz */
    "da", /* da */
    "din", /* db */
    "dao", /* dc */
    "dai", /* dd */
    "de", /* de */
    "den", /* df */
    "deng", /* dg */
    "dang", /* dh */
    "di", /* di */
    "dan", /* dj */
    "ding", /* dk */
    "duang", /* dl */
    "dian", /* dm */
    "diao", /* dn */
    "duo", /* do */
    "die", /* dp */
    "diu", /* dq */
    "duan", /* dr */
    "dong", /* ds */
    "duie", /* dt */
    "du", /* du */
    "dui", /* dv */
    "dei", /* dw */
    "dia", /* dx */
    "dun", /* dy */
    "dou", /* dz */
    "ea", /* ea */
    "ein", /* eb */
    "eao", /* ec */
    "eai", /* ed */
    "ee", /* ee */
    "en", /* ef */
    "eng", /* eg */
    "eang", /* eh */
    "ei", /* ei */
    "ean", /* ej */
    "eing", /* ek */
    "euang", /* el */
    "eian", /* em */
    "en", /* en */
    "eo", /* eo */
    "eie", /* ep */
    "eiu", /* eq */
    "er", /* er */
    "eong", /* es */
    "eve", /* et */
    "eu", /* eu */
    "ev", /* ev */
    "ei", /* ew */
    "eia", /* ex */
    "eun", /* ey */
    "eou", /* ez */
    "fa", /* fa */
    "fin", /* fb */
    "fao", /* fc */
    "fai", /* fd */
    "fe", /* fe */
    "fen", /* ff */
    "feng", /* fg */
    "fang", /* fh */
    "fi", /* fi */
    "fan", /* fj */
    "fing", /* fk */
    "fuang", /* fl */
    "fian", /* fm */
    "fiao", /* fn */
    "fo", /* fo */
    "fie", /* fp */
    "fiu", /* fq */
    "fr", /* fr */
    "fong", /* fs */
    "fve", /* ft */
    "fu", /* fu */
    "fv", /* fv */
    "fei", /* fw */
    "fia", /* fx */
    "fun", /* fy */
    "fou", /* fz */
    "ga", /* ga */
    "gin", /* gb */
    "gao", /* gc */
    "gai", /* gd */
    "ge", /* ge */
    "gen", /* gf */
    "geng", /* gg */
    "gang", /* gh */
    "gi", /* gi */
    "gan", /* gj */
    "guai", /* gk */
    "guang", /* gl */
    "gian", /* gm */
    "gn", /* gn */
    "guo", /* go */
    "gie", /* gp */
    "giu", /* gq */
    "guan", /* gr */
    "gong", /* gs */
    "guie", /* gt */
    "gu", /* gu */
    "gui", /* gv */
    "gei", /* gw */
    "gua", /* gx */
    "gun", /* gy */
    "gou", /* gz */
    "ha", /* ha */
    "hin", /* hb */
    "hao", /* hc */
    "hai", /* hd */
    "he", /* he */
    "hen", /* hf */
    "heng", /* hg */
    "hang", /* hh */
    "hi", /* hi */
    "han", /* hj */
    "huai", /* hk */
    "huang", /* hl */
    "hian", /* hm */
    "hn", /* hn */
    "huo", /* ho */
    "hie", /* hp */
    "hiu", /* hq */
    "huan", /* hr */
    "hong", /* hs */
    "huie", /* ht */
    "hu", /* hu */
    "hui", /* hv */
    "hei", /* hw */
    "hua", /* hx */
    "hun", /* hy */
    "hou", /* hz */
    "cha", /* ia */
    "chin", /* ib */
    "chao", /* ic */
    "chai", /* id */
    "che", /* ie */
    "chen", /* if */
    "cheng", /* ig */
    "chang", /* ih */
    "chi", /* ii */
    "chan", /* ij */
    "chuai", /* ik */
    "chuang", /* il */
    "chian", /* im */
    "chn", /* in */
    "chuo", /* io */
    "chie", /* ip */
    "chiu", /* iq */
    "chuan", /* ir */
    "chong", /* is */
    "chuie", /* it */
    "chu", /* iu */
    "chui", /* iv */
    "chei", /* iw */
    "chua", /* ix */
    "chun", /* iy */
    "chou", /* iz */
    "ja", /* ja */
    "jin", /* jb */
    "jao", /* jc */
    "jai", /* jd */
    "je", /* je */
    "jen", /* jf */
    "jeng", /* jg */
    "jang", /* jh */
    "ji", /* ji */
    "jan", /* jj */
    "jing", /* jk */
    "jiang", /* jl */
    "jian", /* jm */
    "jiao", /* jn */
    "jo", /* jo */
    "jie", /* jp */
    "jiu", /* jq */
    "juan", /* jr */
    "jiong", /* js */
    "jue", /* jt */
    "ju", /* ju */
    "ju", /* jv */
    "jei", /* jw */
    "jia", /* jx */
    "jun", /* jy */
    "jou", /* jz */
    "ka", /* ka */
    "kin", /* kb */
    "kao", /* kc */
    "kai", /* kd */
    "ke", /* ke */
    "ken", /* kf */
    "keng", /* kg */
    "kang", /* kh */
    "ki", /* ki */
    "kan", /* kj */
    "kuai", /* kk */
    "kuang", /* kl */
    "kian", /* km */
    "kn", /* kn */
    "kuo", /* ko */
    "kie", /* kp */
    "kiu", /* kq */
    "kuan", /* kr */
    "kong", /* ks */
    "kuie", /* kt */
    "ku", /* ku */
    "kui", /* kv */
    "kei", /* kw */
    "kua", /* kx */
    "kun", /* ky */
    "kou", /* kz */
    "la", /* la */
    "lin", /* lb */
    "lao", /* lc */
    "lai", /* ld */
    "le", /* le */
    "len", /* lf */
    "leng", /* lg */
    "lang", /* lh */
    "li", /* li */
    "lan", /* lj */
    "ling", /* lk */
    "liang", /* ll */
    "lian", /* lm */
    "liao", /* ln */
    "luo", /* lo */
    "lie", /* lp */
    "liu", /* lq */
    "luan", /* lr */
    "long", /* ls */
    "lüe", /* lt */
    "lu", /* lu */
    "lü", /* lv */
    "lei", /* lw */
    "lia", /* lx */
    "lun", /* ly */
    "lou", /* lz */
    "ma", /* ma */
    "min", /* mb */
    "mao", /* mc */
    "mai", /* md */
    "me", /* me */
    "men", /* mf */
    "meng", /* mg */
    "mang", /* mh */
    "mi", /* mi */
    "man", /* mj */
    "ming", /* mk */
    "muang", /* ml */
    "mian", /* mm */
    "miao", /* mn */
    "mo", /* mo */
    "mie", /* mp */
    "miu", /* mq */
    "mr", /* mr */
    "mong", /* ms */
    "mve", /* mt */
    "mu", /* mu */
    "mv", /* mv */
    "mei", /* mw */
    "mia", /* mx */
    "mun", /* my */
    "mou", /* mz */
    "na", /* na */
    "nin", /* nb */
    "nao", /* nc */
    "nai", /* nd */
    "ne", /* ne */
    "nen", /* nf */
    "neng", /* ng */
    "nang", /* nh */
    "ni", /* ni */
    "nan", /* nj */
    "ning", /* nk */
    "niang", /* nl */
    "nian", /* nm */
    "niao", /* nn */
    "nuo", /* no */
    "nie", /* np */
    "niu", /* nq */
    "nuan", /* nr */
    "nong", /* ns */
    "nüe", /* nt */
    "nu", /* nu */
    "nü", /* nv */
    "nei", /* nw */
    "nia", /* nx */
    "nun", /* ny */
    "nou", /* nz */
    "oa", /* oa */
    "oin", /* ob */
    "oao", /* oc */
    "oai", /* od */
    "oe", /* oe */
    "oen", /* of */
    "oeng", /* og */
    "oang", /* oh */
    "oi", /* oi */
    "oan", /* oj */
    "oing", /* ok */
    "ouang", /* ol */
    "oian", /* om */
    "on", /* on */
    "oo", /* oo */
    "oie", /* op */
    "oiu", /* oq */
    "or", /* or */
    "ong", /* os */
    "ove", /* ot */
    "ou", /* ou */
    "ov", /* ov */
    "oei", /* ow */
    "oia", /* ox */
    "oun", /* oy */
    "ou", /* oz */
    "pa", /* pa */
    "pin", /* pb */
    "pao", /* pc */
    "pai", /* pd */
    "pe", /* pe */
    "pen", /* pf */
    "peng", /* pg */
    "pang", /* ph */
    "pi", /* pi */
    "pan", /* pj */
    "ping", /* pk */
    "puang", /* pl */
    "pian", /* pm */
    "piao", /* pn */
    "po", /* po */
    "pie", /* pp */
    "piu", /* pq */
    "pr", /* pr */
    "pong", /* ps */
    "pve", /* pt */
    "pu", /* pu */
    "pv", /* pv */
    "pei", /* pw */
    "pia", /* px */
    "pun", /* py */
    "pou", /* pz */
    "qa", /* qa */
    "qin", /* qb */
    "qao", /* qc */
    "qai", /* qd */
    "qe", /* qe */
    "qen", /* qf */
    "qeng", /* qg */
    "qang", /* qh */
    "qi", /* qi */
    "qan", /* qj */
    "qing", /* qk */
    "qiang", /* ql */
    "qian", /* qm */
    "qiao", /* qn */
    "qo", /* qo */
    "qie", /* qp */
    "qiu", /* qq */
    "quan", /* qr */
    "qiong", /* qs */
    "que", /* qt */
    "qu", /* qu */
    "qu", /* qv */
    "qei", /* qw */
    "qia", /* qx */
    "qun", /* qy */
    "qou", /* qz */
    "ra", /* ra */
    "rin", /* rb */
    "rao", /* rc */
    "rai", /* rd */
    "re", /* re */
    "ren", /* rf */
    "reng", /* rg */
    "rang", /* rh */
    "ri", /* ri */
    "ran", /* rj */
    "ruai", /* rk */
    "ruang", /* rl */
    "rian", /* rm */
    "rn", /* rn */
    "ruo", /* ro */
    "rie", /* rp */
    "riu", /* rq */
    "ruan", /* rr */
    "rong", /* rs */
    "ruie", /* rt */
    "ru", /* ru */
    "rui", /* rv */
    "rei", /* rw */
    "rua", /* rx */
    "run", /* ry */
    "rou", /* rz */
    "sa", /* sa */
    "sin", /* sb */
    "sao", /* sc */
    "sai", /* sd */
    "se", /* se */
    "sen", /* sf */
    "seng", /* sg */
    "sang", /* sh */
    "si", /* si */
    "san", /* sj */
    "suai", /* sk */
    "suang", /* sl */
    "sian", /* sm */
    "sn", /* sn */
    "suo", /* so */
    "sie", /* sp */
    "siu", /* sq */
    "suan", /* sr */
    "song", /* ss */
    "suie", /* st */
    "su", /* su */
    "sui", /* sv */
    "sei", /* sw */
    "sua", /* sx */
    "sun", /* sy */
    "sou", /* sz */
    "ta", /* ta */
    "tin", /* tb */
    "tao", /* tc */
    "tai", /* td */
    "te", /* te */
    "ten", /* tf */
    "teng", /* tg */
    "tang", /* th */
    "ti", /* ti */
    "tan", /* tj */
    "ting", /* tk */
    "tuang", /* tl */
    "tian", /* tm */
    "tiao", /* tn */
    "tuo", /* to */
    "tie", /* tp */
    "tiu", /* tq */
    "tuan", /* tr */
    "tong", /* ts */
    "tuie", /* tt */
    "tu", /* tu */
    "tui", /* tv */
    "tei", /* tw */
    "tia", /* tx */
    "tun", /* ty */
    "tou", /* tz */
    "sha", /* ua */
    "shin", /* ub */
    "shao", /* uc */
    "shai", /* ud */
    "she", /* ue */
    "shen", /* uf */
    "sheng", /* ug */
    "shang", /* uh */
    "shi", /* ui */
    "shan", /* uj */
    "shuai", /* uk */
    "shuang", /* ul */
    "shian", /* um */
    "shn", /* un */
    "shuo", /* uo */
    "shie", /* up */
    "shiu", /* uq */
    "shuan", /* ur */
    "shong", /* us */
    "shuie", /* ut */
    "shu", /* uu */
    "shui", /* uv */
    "shei", /* uw */
    "shua", /* ux */
    "shun", /* uy */
    "shou", /* uz */
    "zha", /* va */
    "zhin", /* vb */
    "zhao", /* vc */
    "zhai", /* vd */
    "zhe", /* ve */
    "zhen", /* vf */
    "zheng", /* vg */
    "zhang", /* vh */
    "zhi", /* vi */
    "zhan", /* vj */
    "zhuai", /* vk */
    "zhuang", /* vl */
    "zhian", /* vm */
    "zhn", /* vn */
    "zhuo", /* vo */
    "zhie", /* vp */
    "zhiu", /* vq */
    "zhuan", /* vr */
    "zhong", /* vs */
    "zhuie", /* vt */
    "zhu", /* vu */
    "zhui", /* vv */
    "zhei", /* vw */
    "zhua", /* vx */
    "zhun", /* vy */
    "zhou", /* vz */
    "wa", /* wa */
    "win", /* wb */
    "wao", /* wc */
    "wai", /* wd */
    "we", /* we */
    "wen", /* wf */
    "weng", /* wg */
    "wang", /* wh */
    "wi", /* wi */
    "wan", /* wj */
    "wing", /* wk */
    "wuang", /* wl */
    "wian", /* wm */
    "wn", /* wn */
    "wo", /* wo */
    "wie", /* wp */
    "wiu", /* wq */
    "wr", /* wr */
    "wong", /* ws */
    "wve", /* wt */
    "wu", /* wu */
    "wv", /* wv */
    "wei", /* ww */
    "wia", /* wx */
    "wun", /* wy */
    "wou", /* wz */
    "xa", /* xa */
    "xin", /* xb */
    "xao", /* xc */
    "xai", /* xd */
    "xe", /* xe */
    "xen", /* xf */
    "xeng", /* xg */
    "xang", /* xh */
    "xi", /* xi */
    "xan", /* xj */
    "xing", /* xk */
    "xiang", /* xl */
    "xian", /* xm */
    "xiao", /* xn */
    "xo", /* xo */
    "xie", /* xp */
    "xiu", /* xq */
    "xuan", /* xr */
    "xiong", /* xs */
    "xue", /* xt */
    "xu", /* xu */
    "xu", /* xv */
    "xei", /* xw */
    "xia", /* xx */
    "xun", /* xy */
    "xou", /* xz */
    "ya", /* ya */
    "yin", /* yb */
    "yao", /* yc */
    "yai", /* yd */
    "ye", /* ye */
    "yen", /* yf */
    "yeng", /* yg */
    "yang", /* yh */
    "yi", /* yi */
    "yan", /* yj */
    "ying", /* yk */
    "yuang", /* yl */
    "yian", /* ym */
    "yn", /* yn */
    "yo", /* yo */
    "yie", /* yp */
    "yiu", /* yq */
    "yuan", /* yr */
    "yong", /* ys */
    "yue", /* yt */
    "yu", /* yu */
    "yu", /* yv */
    "yei", /* yw */
    "yia", /* yx */
    "yun", /* yy */
    "you", /* yz */
    "za", /* za */
    "zin", /* zb */
    "zao", /* zc */
    "zai", /* zd */
    "ze", /* ze */
    "zen", /* zf */
    "zeng", /* zg */
    "zang", /* zh */
    "zi", /* zi */
    "zan", /* zj */
    "zuai", /* zk */
    "zuang", /* zl */
    "zian", /* zm */
    "zn", /* zn */
    "zuo", /* zo */
    "zie", /* zp */
    "ziu", /* zq */
    "zuan", /* zr */
    "zong", /* zs */
    "zuie", /* zt */
    "zu", /* zu */
    "zui", /* zv */
    "zei", /* zw */
    "zua", /* zx */
    "zun", /* zy */
    "zou", /* zz */
};
